$engine: 3
$onesync: on
name: ESX Legacy
author: thesysadmindev
description: A custom version of the ESX Legacy Recipe with specific versions, because people can't make shit that doesn't break on version upgrades...

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/thesysadmindev/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/thesysadmindev/esx-recipes
    ref: legacy
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/esxLogo.png
    dest: ./esxLogo.png

  # Download basic resources and ESX dependencies

  - action: connect_database

  - action: download_file
    path: ./tmp/files/esx_core.zip
    url: https://github.com/thesysadmindev/esx_core/archive/refs/tags/1.10.10.zip
  - action: unzip
    dest: ./tmp
    src: ./tmp/files/esx_core.zip

  - action: query_database
    file: ./tmp/esx_core-1.10.10/[SQL]/legacy.sql

  - action: download_github
    src: https://github.com/thesysadmindev/ESX-Legacy-Addons
    ref: main
    dest: ./tmp/addons

  - action: move_path
    src: ./tmp/esx_core-1.10.10/[core]
    dest: ./resources/[core]

  - action: move_path
    src: ./tmp/addons/[esx_addons]
    dest: ./resources/[esx_addons]

  - action: download_github
    src: https://github.com/thesysadmindev/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_file
    path: ./tmp/files/pma-voice.zip
    url: https://github.com/thesysadmindev/pma-voice/archive/refs/tags/v6.6.2.zip
  - action: unzip
    dest: ./tmp
    src: ./tmp/files/pma-voice.zip
  - action: move_path
    src: ./tmp/pma-voice-6.6.2
    dest: ./resources/[standalone]/pma-voice

  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/thesysadmindev/oxmysql/archive/refs/tags/v2.13.0.zip
  - action: unzip
    dest: ./tmp
    src: ./tmp/files/oxmysql.zip
  - action: move_path
    src: ./tmp/oxmysql-2.13.0
    dest: ./resources/[standalone]/oxmysql

  ## Cleanup
  - action: remove_path
    path: ./tmp

## Fuck Cockstar... Long live NTAuthority!
